# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFd4L1yIWnBt1cx5uTFbEObemvcTq_IR

# O'zgaruvchilar va ma'lumot turlari
"""

#05 string (matn)

# Yuqoridagi o'zgaruvchilarni jamlab, quyidagi ko'rinishda konsolga chiqaring:
# Bog'bon ko'chasi, Sog'bon mahallasi, Bodomzor tumani, Samarqand viloyati
kocha = input("Ko'changizning nomini kiriting: ")
mahalla = input("Mahallangizning nomini kiriting: ")
tuman = input("Tumaningizning nomini kiriting: ")
viloyat = input("Viloyatingizning nomini kiriting: ")
manzil = f"Quyidagi ma'lumotlaringiz to'g'riligini tekshiring: \n{kocha} ko'chasi, {mahalla} mahallasi, {tuman} tumani, {viloyat} viloyati"
print(manzil.capitalize())
# Yuqoridagi matnni 'manzil' degan o'zgaruvchi yuklaymiz